default_stages: [push]

repos:
  - repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pytest tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]

      - id: black
        name: Check black code formating
        entry: black --check _pytest_easy_addoption easy_addoption tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]

      - id: mypy
        name: Check mypy static types match
        entry: mypy _pytest_easy_addoption easy_addoption
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]

      - id: flake8
        name: Check flake8 rules match
        entry: flake8 _pytest_easy_addoption easy_addoption tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]
