language: python

install:
  - pip install ".[dev]"

env:
  - TEST_CMD="pytest tests"
  - SRC_DIR="pytest_easy_addoption"

script:
  - $TEST_CMD

matrix:
  include:
#    - name: "flake8"
#      python: 3.6
#      env:
#        - TEST_CMD="flake8 $SRC_DIR"

#    - name: "mypy"
#      python: "3.6"
#      env:
#        - TEST_CMD="mypy $SRC_DIR"

    - name: "codecov"
      python: "3.6"
      env:
        - TEST_CMD="pytest --cov-report term --cov=$SRC_DIR tests"
      after_success:
        - curl -s https://codecov.io/bash | bash

    - name: "3.6"
      python: "3.6"

    - name: "3.7"
      python: "3.7"

    - name: "3.8"
      python: "3.8"
